### PR TITLE
feat:Providing an interface for utilizing the XY Plot externally.

### PR DESCRIPTION
**Pull request by ltdrdata**
**Main:**
I have implemented an XY Input to assist with LoraBlockWeight. To achieve this, I have created an external exposed interface called XY_Capsule.

**Additional:**
While implementing and testing the XY Input, I encountered an issue where the model and clip did not reset to their initial states during each x, y loop iteration. Instead, they accumulated over time. I have fixed this issue.
(Code related to "original_model" and "original_clip")

I have fixed the code to ensure proper functionality of the newly implemented XY Input. However, I kindly request clarification on whether this behavior was intentional or an issue that needed to be addressed.

**Result:**
The application of this feature can be tested through custom nodes in the following repository: https://github.com/ltdrdata/ComfyUI-Impact-Exp.

xyplot

### CODE REVIEW

**Comment by LucianoCirino** [comment]
Hello @ltdrdata, the model and clip not being reset back to their defaults between XY plot image generations was a design choice, however, outputting the possibly modified model and conditionings was not, this is an oversight on my part and I need to fix this. 

Below are my questions..

1) does doing this:
```
model = original_model.clone()
```
not duplicate the model in RAM while the XY plotter is running (even if not necessary?). Not sure if this is good practice or not, asking for your opinion :)

______________________________________________________
2) Is the XY capsule basically a way for you to inject your own custom generation parameters into the XY Plot script?

______________________________________________________
3) I am actually not entirely sure what LoRA block weights are, but I trust you, looks neat. 

______________________________________________________

Oh and fyi...I am actually about to do a huge update today to the repo, but from reviewing all the things in your PR it doesn't look like there should be any conflicts if I chose to proceed with it...

**Comment by ltdrdata** [comment]
"Lora Block Weight" is a feature that allows adjusting the impact of different blocks within Lora when patching the model. It's generally used when you want to utilize only specific learning attributes of Lora. It serves the purpose of selectively blocking aspects like learned clothing, poses, or artistic styles while training a character. Particularly, when mixing multiple Loras, this feature can help mitigate issues with generated images being distorted.

Since the actual influence of blocking certain blocks depends on the learned state, there's a need to visualize the effects of weight control through XYPlot.

The XY capsule is a functionality that enables injecting elements beyond the default XY parameters into the XY Plot, making them usable within that context. Currently, based on the functionality of Lora Block Weight, we've added a minimal interface to XY capsules, but it's possible to expand further as needed.

Cloning the model unconditionally was implemented in the simplest form due to the unclear design decision for that aspect. Upon reviewing the fixes in the main branch, I will proceed to make the necessary modifications for that part.

**Comment by ltdrdata** [comment]
The testing after the merge is complete.

Regarding the `model.clone` part, upon investigation, it was found that it doesn't replicate the entire actual model data. Therefore, there's no need to be concerned about memory impact.

When loading Lora, the process entails invoking 'clone' on the base model in the same manner and then configuring the patch information.

**Comment by LucianoCirino** [comment]
Great, thanks for testing out the Model cloning concern I had.

**Pull request merged**
