### PR TITLE
control preview grid images in Ksampler, instead in .json

### PR DESCRIPTION
**Pull request by DorotaLuna**
I think put this setting in .json is a bit of annoying.
Every time I want to change this setting I need to open the .json and reload the comfyui.

### CODE REVIEW

**Comment by DorotaLuna** [comment]
> 

I think you mean like this:
"preview_image": (["Disabled", "Enabled", "Grid"],),
then check the "preview_image" state whether is not equal to "Grid" when output grid images.

**Comment by LucianoCirino** [comment]
How would you feel if this option is moved onto the XY Plot node itself?

**Comment by DorotaLuna** [comment]
> How would you feel if this option is moved onto the XY Plot node itself?

I don't think it's a good idea, this means XY Plot can control the reference of the node next to the next node.
I think that's a bit of counterintuitive, because the Image output is on Ksampler node so this should be controled by Ksampler.

**Comment by LucianoCirino** [comment]
I appreciate the pull request and the comments but unfortunately I ended up setting it up with the option moved to the XY Plot node. The reasoning is that I have added a new option in the Ksampler's preview_image selector with the option "Output Only" which made it difficult to apply what you requested without adding variables to the Ksampler (which I really don't want to do). Hopefully my solution at least meets the intent.

image

**Pull request closed without merging**
