### PR TITLE
Enable hot-reload of lora, checkpoint, sampler, scheduler, vae

### PR DESCRIPTION
**Pull request by Mijago**
This very simple change allows us to add lora, checkpoint, sampler, scheduler and vae without the need to restart the entire application. I simply moved the static variables to the `INPUT_TYPES` method.

### CODE REVIEW

**Comment by LucianoCirino** [comment]
@Mijago, I don't really understand. Wether I use your PR version of the nodes or not, I have to refresh the webpage for the dropdown settings to update. Could you please give me an example to test?

**Comment by Mijago** [comment]
I mostly use the 'Reload' button in ComfyUIs menu. As the variables of Lora/Checkpoint/etc are stored in the class itself, it will not be updated until I restart it. 
My issue here is that with a restart I lose time, and with a page reload I lose the shown temp-images. It's mainly a QoL change.

**Comment by LucianoCirino** [comment]
> I mostly use the 'Reload' button in ComfyUIs menu. As the variables of Lora/Checkpoint/etc are stored in the class itself, it will not be updated until I restart it. My issue here is that with a restart I lose time, and with a page reload I lose the shown temp-images. It's mainly a QoL change.

I just tested what you are trying to fix on the current github repo version by moving a lora model out of the model folder and clicking "refresh" on the UI and it updated the dropdown menu?? I am confused on why it updates for me. What browser are you running comfyui on?

**Comment by LucianoCirino** [comment]
Oh nvm ive replicated the issue lol

**Comment by Mijago** [comment]
I think it is mainly happening in XY-Plots.
I wanted to compare different lora versions, and always reloading/restarting was quite annoying to me, hence the PR :)

**Review by LucianoCirino — APPROVED** [review]
Just tested. Works perfect. Sorry for the delay been extremely busy.

**Pull request merged**
