### PR TITLE
Rewrote X/Y LoRA weights for the new update

### PR DESCRIPTION
**Pull request by Zuke97**
also made general X/Y LoRAs work, had to tweak caching, axis labeling to get to it work
X/Y weights support background common LoRAs - see example pics
added info panel for X/Y weight image grids in the upper left corner, might be useful for other grids?

could probably cache the LoRAs better for the X/Y weight changing but not sure if it's worth it

original: https://github.com/LucianoCirino/efficiency-nodes-comfyui/pull/35
accidentally closed it myself...

### CODE REVIEW

**Comment by LucianoCirino** [comment]
Hey @Zuke97 , why did you back out of making this into a node? I think setting all this logic up through a node was a much better idea. See the picture below for reference.

image

**Comment by Zuke97** [comment]
i like it, the actual node functionality can just mimic the current setup but in one nice easy to use node. hijacking the X/Y value lists was most of the work anyway. 

A thought i just had (and will have to test later) is loading a LoRA with model weight 0.75 and clip weight 0.5 the same as loading both a LoRA with model 0.0/clip 0.5 and a LoRA with model 0.75/clip 0.0. if so that would be way easier than what i did, but I don't know enough about how these actually work to know

**Comment by Zuke97** [comment]
had to add extra X/Y types for it to go nicely but it's definitely cleaner this way

**Comment by LucianoCirino** [comment]
This has been implemented another way. Closing this PR.

**Pull request closed without merging**
